"use client";

import type React from "react";
import { createContext, useContext, useState, useEffect } from "react";
import { useLocalStorage } from "@/hooks/use-local-storage";

type Language = "en" | "ru" | "uz" | "kz" | "kg" | "tj" | "cn";
type Currency = "USD" | "RUB" | "UZS" | "KZT" | "KGS" | "TJS" | "CNY";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  t: (key: string) => string;
}

const languageCurrencyMap: Record<Language, Currency> = {
  en: "USD",
  ru: "RUB",
  uz: "UZS",
  kz: "KZT",
  kg: "KGS",
  tj: "TJS",
  cn: "CNY",
};

// Currency conversion rates (simplified for demo)
const currencyRates: Record<Currency, number> = {
  USD: 1,
  RUB: 80,
  UZS: 12000,
  KZT: 450,
  KGS: 90,
  TJS: 12,
  CNY: 7,
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome",
    login: "Login",
    register: "Register",
    dashboard: "Dashboard",
    profile: "Profile",
    earnings: "Earnings",
    referrals: "Referrals",
    tariffs: "Tariff Plans",
    withdrawal: "Withdrawal",
    spin: "Spin Game",
    support: "Support",
    phone: "Phone Number",
    password: "Password",
    verify: "Verify",
    submit: "Submit",
    name: "Name",
    activeTariff: "Active Tariff",
    daysRemaining: "Days Remaining",
    dailyEarnings: "Daily Earnings",
    monthlyEarnings: "Monthly Earnings",
    invitedFriends: "Invited Friends",
    paymentStatus: "Payment Status",
    purchase: "Purchase",
    pay: "Pay",
    waitPayment:
      "Please wait. Payment card number will be provided within 2 minutes",
    completePayment: "Complete payment and upload receipt within 10 minutes",
    uploadReceipt: "Upload Receipt",
    cardNumber: "Card Number",
    requestWithdrawal: "Request Withdrawal",
    minimumAmount: "Minimum amount",
    pending: "Pending",
    processed: "Processed",
    freeSpin: "Free Spin",
    spinCount: "Spin Count",
    share: "Share",
    notFound: "404 Not Found",
    backToHome: "Back to Home",
    start: "Start",
    silver: "Silver",
    gold: "Gold",
    price: "Price",
    duration: "Duration",
    dailyProfit: "Daily Profit",
    description: "Description",
    days: "days",
    or: "Or",
    with: "with",
    email: "Email",
    optional: "Optional",
    verificationCodeSent: "Verification code sent to:",
    yourReferralLink: "Your Referral Link",
    copyLink: "Copy Link",
    linkCopied: "Link copied to clipboard!",
    shareVia: "Share via",
    referralStats: "Referral Statistics",
    totalReferrals: "Total Referrals",
    activeReferrals: "Active Referrals",
    referralEarnings: "Referral Earnings",
    productPrice: "Product Price",
    dailyIncome: "Daily Income",
    incomeDuration: "Income Duration",
    totalIncome: "Total Income",
    tariffPrice: "Tariff Price",
    information: "Information",
    changePassword: "Change Password",
    changePasswordDesc: "Update your password to keep your account secure",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    changing: "Changing...",
    editPersonalInfo: "Edit your personal information",
    yourPersonalInfo: "Your personal information",
    cancel: "Cancel",
    saveProfile: "Save Profile",
    editProfile: "Edit Profile",
    userId: "User ID",
    editCardInfo: "Edit your card information",
    manageCardInfo: "Manage your payment card",
    expiryDate: "Expiry Date",
    expires: "Expires",
    saveCard: "Save Card",
    editCard: "Edit Card",
    addCard: "Add Card",
    earningsHistory: "Earnings History",
    registeredSince: "Registered since",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    aboutUs: "About Us",
    aboutUsDesc: "Learn more about our MLM platform and how it works",
    ourMission: "Our Mission",
    ourMissionDesc:
      "Our mission is to provide a transparent and profitable MLM platform for everyone. We believe in creating opportunities for financial growth through quality products and a fair compensation plan.",
    ourMissionDesc2:
      "We are committed to offering premium health and beauty products while enabling our partners to build sustainable businesses and achieve financial independence.",
    howItWorks: "How It Works",
    joinUs: "Join Us",
    joinUsDesc:
      "Register on our platform and create your personal account. It's free and takes only a few minutes.",
    chooseTariff: "Choose a Tariff",
    chooseTariffDesc:
      "Select a tariff plan that suits your goals and budget. Each plan offers different benefits and earning potential.",
    earnMoney: "Earn Money",
    earnMoneyDesc:
      "Start earning daily income from your tariff and build your network to increase your earnings through referrals.",
    readyToStart: "Ready to Start?",
    readyToStartDesc:
      "Join thousands of successful partners who are already earning with our MLM platform.",
    getStarted: "Get Started",
    viewTariffs: "View Tariffs",
    products: "Products",
    about: "About",
    referralBonusInfo:
      "You'll earn bonuses when your referrals register and add funds to their balance.",
    shareReferralLink: "Share Referral Link",
    copied: "Copied!",
    referralLinkCopied: "Referral link copied to clipboard!",
    joinMlmPlatform: "Join MLM Platform",
    joinMeOnMlm: "Join me on MLM Platform and start earning!",
    selectCard: "Select Card",
    amount: "Amount",
    availableBalance: "Available balance",
    processing: "Processing...",
    withdrawalHistory: "Withdrawal History",
    withdrawalPendingApproval:
      "Your withdrawal request is pending administrator approval.",
    addNewCard: "Add New Card",
    skincare: "Skincare",
    supplements: "Supplements",
    wellness: "Wellness",
    category: "Category",
    quantity: "Quantity",
    addToCart: "Add to Cart",
    addToWishlist: "Add to Wishlist",
    features: "Features",
    usage: "Usage",
    ingredients: "Ingredients",
    relatedProducts: "Related Products",
    reviews: "reviews",
    viewDetails: "View Details",
    home: "Home",
    productNotFound: "Product Not Found",
    productNotFoundDesc:
      "The product you are looking for does not exist or has been removed.",
    backToProducts: "Back to Products",
    addedToCart: "Added to Cart",
    addedToCartDesc: "has been added to your cart",
    addedToWishlist: "Added to Wishlist",
    addedToWishlistDesc: "has been added to your wishlist",
    active_users: "Active Users",
    loading_users: "Loading users...",
  },
  ru: {
    welcome: "Добро пожаловать",
    login: "Вход",
    register: "Регистрация",
    dashboard: "Панель управления",
    profile: "Профиль",
    earnings: "Заработок",
    referrals: "Рефералы",
    tariffs: "Тарифные планы",
    withdrawal: "Вывод средств",
    spin: "Игра Спин",
    support: "Поддержка",
    phone: "Номер телефона",
    password: "Пароль",
    verify: "Проверить",
    submit: "Отправить",
    name: "Имя",
    activeTariff: "Активный тариф",
    daysRemaining: "Осталось дней",
    dailyEarnings: "Ежедневный заработок",
    monthlyEarnings: "Ежемесячный заработок",
    invitedFriends: "Приглашенные друзья",
    paymentStatus: "Статус оплаты",
    purchase: "Купить",
    pay: "Оплатить",
    waitPayment:
      "Пожалуйста, подождите. Номер карты будет предоставлен в течение 2 минут",
    completePayment:
      "Завершите оплату и загрузите квитанцию в течение 10 минут",
    uploadReceipt: "Загрузить квитанцию",
    cardNumber: "Номер карты",
    requestWithdrawal: "Запросить вывод",
    minimumAmount: "Минимальная сумма",
    pending: "В ожидании",
    processed: "Обработано",
    freeSpin: "Бесплатное вращение",
    spinCount: "Количество вращений",
    share: "Поделиться",
    notFound: "404 Страница не найдена",
    backToHome: "Вернуться на главную",
    start: "Старт",
    silver: "Серебро",
    gold: "Золото",
    price: "Цена",
    duration: "Длительность",
    dailyProfit: "Ежедневная прибыль",
    description: "Описание",
    days: "дней",
    or: "Или",
    with: "с помощью",
    email: "Электронная почта",
    optional: "Необязательно",
    verificationCodeSent: "Код подтверждения отправлен на:",
    yourReferralLink: "Ваша реферальная ссылка",
    copyLink: "Копировать ссылку",
    linkCopied: "Ссылка скопирована в буфер обмена!",
    shareVia: "Поделиться через",
    referralStats: "Статистика рефералов",
    totalReferrals: "Всего рефералов",
    activeReferrals: "Активные рефералы",
    referralEarnings: "Заработок с рефералов",
    productPrice: "Цена продукта",
    dailyIncome: "Ежедневный доход",
    incomeDuration: "Срок дохода",
    totalIncome: "Общий доход",
    tariffPrice: "Цена тарифа",
    information: "Информация",
    changePassword: "Изменить пароль",
    changePasswordDesc:
      "Обновите свой пароль для обеспечения безопасности аккаунта",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите пароль",
    changing: "Изменение...",
    editPersonalInfo: "Редактировать личную информацию",
    yourPersonalInfo: "Ваша личная информация",
    cancel: "Отмена",
    saveProfile: "Сохранить профиль",
    editProfile: "Редактировать профиль",
    userId: "ID пользователя",
    editCardInfo: "Редактировать информацию о карте",
    manageCardInfo: "Управление платежной картой",
    expiryDate: "Срок действия",
    expires: "Истекает",
    saveCard: "Сохранить карту",
    editCard: "Редактировать карту",
    addCard: "Добавить карту",
    earningsHistory: "История заработка",
    registeredSince: "Зарегистрирован с",
    daily: "Ежедневно",
    weekly: "Еженедельно",
    monthly: "Ежемесячно",
    aboutUs: "О нас",
    aboutUsDesc: "Узнайте больше о нашей MLM платформе и как она работает",
    ourMission: "Наша миссия",
    ourMissionDesc:
      "Наша миссия - предоставить прозрачную и прибыльную MLM платформу для всех. Мы верим в создание возможностей для финансового роста через качественные продукты и справедливый план вознаграждения.",
    ourMissionDesc2:
      "Мы стремимся предлагать премиальные продукты для здоровья и красоты, позволяя нашим партнерам строить устойчивый бизнес и достигать финансовой независимости.",
    howItWorks: "Как это работает",
    joinUs: "Присоединяйтесь к нам",
    joinUsDesc:
      "Зарегистрируйтесь на нашей платформе и создайте личный аккаунт. Это бесплатно и занимает всего несколько минут.",
    chooseTariff: "Выберите тариф",
    chooseTariffDesc:
      "Выберите тарифный план, который соответствует вашим целям и бюджету. Каждый план предлагает различные преимущества и потенциал заработка.",
    earnMoney: "Зарабатывайте деньги",
    earnMoneyDesc:
      "Начните получать ежедневный доход от вашего тарифа и развивайте свою сеть, чтобы увеличить заработок через рефералов.",
    readyToStart: "Готовы начать?",
    readyToStartDesc:
      "Присоединяйтесь к тысячам успешных партнеров, которые уже зарабатывают с нашей MLM платформой.",
    getStarted: "Начать",
    viewTariffs: "Посмотреть тарифы",
    products: "Продукты",
    about: "О нас",
    referralBonusInfo:
      "Вы будете получать бонусы, когда ваши рефералы регистрируются и пополняют свой баланс.",
    shareReferralLink: "Поделиться реферальной ссылкой",
    copied: "Скопировано!",
    referralLinkCopied: "Реферальная ссылка скопирована в буфер обмена!",
    joinMlmPlatform: "Присоединяйтесь к MLM платформе",
    joinMeOnMlm:
      "Присоединяйтесь ко мне на MLM платформе и начните зарабатывать!",
    selectCard: "Выберите карту",
    amount: "Сумма",
    availableBalance: "Доступный баланс",
    processing: "Обработка...",
    withdrawalHistory: "История выводов",
    withdrawalPendingApproval:
      "Ваш запрос на вывод средств ожидает одобрения администратора.",
    addNewCard: "Добавить новую карту",
    skincare: "Уход за кожей",
    supplements: "Добавки",
    wellness: "Здоровье",
    category: "Категория",
    quantity: "Количество",
    addToCart: "Добавить в корзину",
    addToWishlist: "Добавить в избранное",
    features: "Особенности",
    usage: "Применение",
    ingredients: "Ингредиенты",
    relatedProducts: "Похожие продукты",
    reviews: "отзывов",
    viewDetails: "Подробнее",
    home: "Главная",
    productNotFound: "Товар не найден",
    productNotFoundDesc:
      "Товар, который вы ищете, не существует или был удален.",
    backToProducts: "Назад к продуктам",
    addedToCart: "Добавлено в корзину",
    addedToCartDesc: "добавлен в вашу корзину",
    addedToWishlist: "Добавлено в избранное",
    addedToWishlistDesc: "добавлен в ваше избранное",
    active_users: "Активные пользователи",
    loading_users: "Загрузка пользователей...",
  },
  uz: {
    welcome: "Xush kelibsiz",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    dashboard: "Boshqaruv paneli",
    profile: "Profil",
    earnings: "Daromad",
    referrals: "Referallar",
    tariffs: "Tarif rejalar",
    withdrawal: "Pul yechish",
    spin: "Spin o'yini",
    support: "Yordam",
    phone: "Telefon raqami",
    password: "Parol",
    verify: "Tekshirish",
    submit: "Yuborish",
    name: "Ism",
    activeTariff: "Aktiv tarif",
    daysRemaining: "Qolgan kunlar",
    dailyEarnings: "Kunlik daromad",
    monthlyEarnings: "Oylik daromad",
    invitedFriends: "Taklif qilingan do'stlar",
    paymentStatus: "To'lov holati",
    purchase: "Sotib olish",
    pay: "To'lash",
    waitPayment: "Iltimos, kuting. Karta raqami 2 daqiqa ichida taqdim etiladi",
    completePayment:
      "To'lovni yakunlang va 10 daqiqa ichida kvitansiyani yuklang",
    uploadReceipt: "Kvitansiyani yuklash",
    cardNumber: "Karta raqami",
    requestWithdrawal: "Pul yechishni so'rash",
    minimumAmount: "Minimal miqdor",
    pending: "Kutilmoqda",
    processed: "Qayta ishlandi",
    freeSpin: "Bepul aylanish",
    spinCount: "Aylanishlar soni",
    share: "Ulashish",
    notFound: "404 Sahifa topilmadi",
    backToHome: "Bosh sahifaga qaytish",
    start: "Boshlash",
    silver: "Kumush",
    gold: "Oltin",
    price: "Narx",
    duration: "Davomiyligi",
    dailyProfit: "Kunlik foyda",
    description: "Tavsif",
    days: "kun",
    or: "Yoki",
    with: "orqali",
    email: "Elektron pochta",
    optional: "Ixtiyoriy",
    verificationCodeSent: "Tasdiqlash kodi yuborildi:",
    yourReferralLink: "Sizning referal havolangiz",
    copyLink: "Havolani nusxalash",
    linkCopied: "Havola nusxalandi!",
    shareVia: "Ulashish",
    referralStats: "Referal statistikasi",
    totalReferrals: "Jami referallar",
    activeReferrals: "Faol referallar",
    referralEarnings: "Referal daromadi",
    productPrice: "Mahsulot narxi",
    dailyIncome: "Kunlik daromad",
    incomeDuration: "Daromad muddati",
    totalIncome: "Umumiy daromad",
    tariffPrice: "Tarif narxi",
    information: "Ma'lumot",
    changePassword: "Parolni o'zgartirish",
    changePasswordDesc:
      "Hisobingiz xavfsizligini ta'minlash uchun parolingizni yangilang",
    currentPassword: "Joriy parol",
    newPassword: "Yangi parol",
    confirmPassword: "Parolni tasdiqlang",
    changing: "O'zgartirilmoqda...",
    editPersonalInfo: "Shaxsiy ma'lumotlarni tahrirlash",
    yourPersonalInfo: "Sizning shaxsiy ma'lumotlaringiz",
    cancel: "Bekor qilish",
    saveProfile: "Profilni saqlash",
    editProfile: "Profilni tahrirlash",
    userId: "Foydalanuvchi ID",
    editCardInfo: "Karta ma'lumotlarini tahrirlash",
    manageCardInfo: "To'lov kartasini boshqarish",
    expiryDate: "Amal qilish muddati",
    expires: "Muddati",
    saveCard: "Kartani saqlash",
    editCard: "Kartani tahrirlash",
    addCard: "Karta qo'shish",
    earningsHistory: "Daromad tarixi",
    registeredSince: "Ro'yxatdan o'tgan sana",
    daily: "Kunlik",
    weekly: "Haftalik",
    monthly: "Oylik",
    aboutUs: "Biz haqimizda",
    aboutUsDesc:
      "MLM platformamiz va uning ishlash tartibi haqida ko'proq ma'lumot oling",
    ourMission: "Bizning vazifamiz",
    ourMissionDesc:
      "Bizning vazifamiz - barcha uchun shaffof va daromadli MLM platformasini taqdim etish. Biz sifatli mahsulotlar va adolatli mukofot rejasi orqali moliyaviy o'sish imkoniyatlarini yaratishga ishonamiz.",
    ourMissionDesc2:
      "Biz hamkorlarimizga barqaror biznes qurish va moliyaviy mustaqillikka erishish imkoniyatini berish bilan birga, sog'liq va go'zallik uchun premium mahsulotlarni taklif etishga intilamiz.",
    howItWorks: "Bu qanday ishlaydi",
    joinUs: "Bizga qo'shiling",
    joinUsDesc:
      "Platformamizda ro'yxatdan o'ting va shaxsiy hisobingizni yarating. Bu bepul va atigi bir necha daqiqa vaqt oladi.",
    chooseTariff: "Tarifni tanlang",
    chooseTariffDesc:
      "Maqsadlaringiz va byudjetingizga mos keladigan tarif rejasini tanlang. Har bir reja turli afzalliklar va daromad imkoniyatlarini taklif etadi.",
    earnMoney: "Pul ishlang",
    earnMoneyDesc:
      "Tarifingizdan kunlik daromad olishni boshlang va referallar orqali daromadingizni oshirish uchun tarmoqingizni rivojlantiring.",
    readyToStart: "Boshlashga tayyormisiz?",
    readyToStartDesc:
      "MLM platformamiz bilan allaqachon pul ishlayotgan minglab muvaffaqiyatli hamkorlarga qo'shiling.",
    getStarted: "Boshlash",
    viewTariffs: "Tariflarni ko'rish",
    products: "Mahsulotlar",
    about: "Biz haqimizda",
    referralBonusInfo:
      "Referallaringiz ro'yxatdan o'tganda va balanslarini to'ldirganda bonus olasiz.",
    shareReferralLink: "Referal havolani ulashish",
    copied: "Nusxalandi!",
    referralLinkCopied: "Referal havola nusxalandi!",
    joinMlmPlatform: "MLM platformasiga qo'shiling",
    joinMeOnMlm:
      "MLM platformasida menga qo'shiling va pul ishlashni boshlang!",
    selectCard: "Kartani tanlang",
    amount: "Miqdor",
    availableBalance: "Mavjud balans",
    processing: "Ishlov berilmoqda...",
    withdrawalHistory: "Pul yechish tarixi",
    withdrawalPendingApproval:
      "Pul yechish so'rovingiz administrator tomonidan tasdiqlanishini kutmoqda.",
    addNewCard: "Yangi karta qo'shish",
    skincare: "Teri parvarishi",
    supplements: "Qo'shimchalar",
    wellness: "Salomatlik",
    category: "Kategoriya",
    quantity: "Miqdor",
    addToCart: "Savatga qo'shish",
    addToWishlist: "Sevimlilar ro'yxatiga qo'shish",
    features: "Xususiyatlar",
    usage: "Qo'llash",
    ingredients: "Tarkibi",
    relatedProducts: "O'xshash mahsulotlar",
    reviews: "sharhlar",
    viewDetails: "Batafsil",
    home: "Bosh sahifa",
    productNotFound: "Mahsulot topilmadi",
    productNotFoundDesc:
      "Siz qidirayotgan mahsulot mavjud emas yoki olib tashlangan.",
    backToProducts: "Mahsulotlarga qaytish",
    addedToCart: "Savatga qo'shildi",
    addedToCartDesc: "savatga qo'shildi",
    addedToWishlist: "Sevimlilarga qo'shildi",
    addedToWishlistDesc: "sevimlilar ro'yxatiga qo'shildi",
    active_users: "Faol foydalanuvchilar",
    loading_users: "Foydalanuvchilar yuklanmoqda...",
  },
  kz: {
    welcome: "Қош келдіңіз",
    login: "Кіру",
    register: "Тіркелу",
    dashboard: "Басқару тақтасы",
    profile: "Профиль",
    earnings: "Табыс",
    referrals: "Рефералдар",
    tariffs: "Тариф жоспарлары",
    withdrawal: "Ақша шығару",
    spin: "Спин ойыны",
    support: "Қолдау",
    phone: "Телефон нөмірі",
    password: "Құпия сөз",
    verify: "Тексеру",
    submit: "Жіберу",
    name: "Аты",
    activeTariff: "Белсенді тариф",
    daysRemaining: "Қалған күндер",
    dailyEarnings: "Күнделікті табыс",
    monthlyEarnings: "Айлық табыс",
    invitedFriends: "Шақырылған достар",
    paymentStatus: "Төлем күйі",
    purchase: "Сатып алу",
    pay: "Төлеу",
    waitPayment: "Күте тұрыңыз. Карта нөмірі 2 минут ішінде беріледі",
    completePayment: "Төлемді аяқтап, 10 минут ішінде түбіртекті жүктеңіз",
    uploadReceipt: "Түбіртекті жүктеу",
    cardNumber: "Карта нөмірі",
    requestWithdrawal: "Ақша шығаруды сұрау",
    minimumAmount: "Ең аз сома",
    pending: "Күтілуде",
    processed: "Өңделді",
    freeSpin: "Тегін айналдыру",
    spinCount: "Айналдыру саны",
    share: "Бөлісу",
    notFound: "404 Бет табылмады",
    backToHome: "Басты бетке оралу",
    start: "Бастау",
    silver: "Күміс",
    gold: "Алтын",
    price: "Баға",
    duration: "Ұзақтығы",
    dailyProfit: "Күнделікті пайда",
    description: "Сипаттама",
    days: "күн",
    or: "Немесе",
    with: "арқылы",
    email: "Электрондық пошта",
    optional: "Міндетті емес",
    verificationCodeSent: "Растау коды жіберілді:",
    yourReferralLink: "Сіздің реферал сілтемеңіз",
    copyLink: "Сілтемені көшіру",
    linkCopied: "Сілтеме көшірілді!",
    shareVia: "Бөлісу",
    referralStats: "Реферал статистикасы",
    totalReferrals: "Барлық рефералдар",
    activeReferrals: "Белсенді рефералдар",
    referralEarnings: "Реферал табысы",
    productPrice: "Өнім бағасы",
    dailyIncome: "Күнделікті табыс",
    incomeDuration: "Табыс мерзімі",
    totalIncome: "Жалпы табыс",
    tariffPrice: "Тариф бағасы",
    information: "Ақпарат",
    changePassword: "Құпия сөзді өзгерту",
    changePasswordDesc:
      "Тіркелгіңіздің қауіпсіздігін қамтамасыз ету үшін құпия сөзіңізді жаңартыңыз",
    currentPassword: "Ағымдағы құпия сөз",
    newPassword: "Жаңа құпия сөз",
    confirmPassword: "Құпия сөзді растау",
    changing: "Өзгертілуде...",
    editPersonalInfo: "Жеке ақпаратты өңдеу",
    yourPersonalInfo: "Сіздің жеке ақпаратыңыз",
    cancel: "Болдырмау",
    saveProfile: "Профильді сақтау",
    editProfile: "Профильді өңдеу",
    userId: "Пайдаланушы ID",
    editCardInfo: "Карта ақпаратын өңдеу",
    manageCardInfo: "Төлем картасын басқару",
    expiryDate: "Жарамдылық мерзімі",
    expires: "Мерзімі",
    saveCard: "Картаны сақтау",
    editCard: "Картаны өңдеу",
    addCard: "Карта қосу",
    earningsHistory: "Табыс тарихы",
    registeredSince: "Тіркелген күні",
    daily: "Күнделікті",
    weekly: "Апта сайын",
    monthly: "Ай сайын",
    aboutUs: "Біз туралы",
    aboutUsDesc:
      "MLM платформамыз және оның жұмыс істеу тәртібі туралы көбірек білу",
    ourMission: "Біздің миссиямыз",
    ourMissionDesc:
      "Біздің миссиямыз - барлығына ашық және табысты MLM платформасын ұсыну. Біз сапалы өнімдер мен әділ сыйақы жоспары арқылы қаржылық өсу мүмкіндіктерін жасауға сенеміз.",
    ourMissionDesc2:
      "Біз серіктестерімізге тұрақты бизнес құруға және қаржылық тәуелсіздікке қол жеткізуге мүмкіндік бере отырып, денсаулық пен сұлулық үшін премиум өнімдерді ұсынуға тырысамыз.",
    howItWorks: "Бұл қалай жұмыс істейді",
    joinUs: "Бізге қосылыңыз",
    joinUsDesc:
      "Платформамызда тіркеліп, жеке шотыңызды жасаңыз. Бұл тегін және бірнеше минут уақыт алады.",
    chooseTariff: "Тарифті таңдаңыз",
    chooseTariffDesc:
      "Мақсаттарыңыз бен бюджетіңізге сәйкес келетін тариф жоспарын таңдаңыз. Әр жоспар әртүрлі артықшылықтар мен табыс мүмкіндіктерін ұсынады.",
    earnMoney: "Ақша табыңыз",
    earnMoneyDesc:
      "Тарифіңізден күнделікті табыс алуды бастаңыз және рефералдар арқылы табысыңызды арттыру үшін желіңізді дамытыңыз.",
    readyToStart: "Бастауға дайынсыз ба?",
    readyToStartDesc:
      "MLM платформамызбен қазірдің өзінде ақша табатын мыңдаған табысты серіктестерге қосылыңыз.",
    getStarted: "Бастау",
    viewTariffs: "Тарифтерді көру",
    products: "Өнімдер",
    about: "Біз туралы",
    referralBonusInfo:
      "Рефералдарыңыз тіркелгенде және балансын толтырғанда бонус аласыз.",
    shareReferralLink: "Реферал сілтемесін бөлісу",
    copied: "Көшірілді!",
    referralLinkCopied: "Реферал сілтемесі көшірілді!",
    joinMlmPlatform: "MLM платформасына қосылыңыз",
    joinMeOnMlm: "MLM платформасында маған қосылып, ақша табуды бастаңыз!",
    selectCard: "Картаны таңдаңыз",
    amount: "Сома",
    availableBalance: "Қолжетімді баланс",
    processing: "Өңделуде...",
    withdrawalHistory: "Ақша шығару тарихы",
    withdrawalPendingApproval: "Ақша шығару сұрауыңыз әкімші бекітуін күтуде.",
    addNewCard: "Жаңа карта қосу",
    skincare: "Тері күтімі",
    supplements: "Қоспалар",
    wellness: "Денсаулық",
    category: "Санат",
    quantity: "Саны",
    addToCart: "Себетке қосу",
    addToWishlist: "Таңдаулыларға қосу",
    features: "Ерекшеліктері",
    usage: "Қолдану",
    ingredients: "Құрамы",
    relatedProducts: "Ұқсас өнімдер",
    reviews: "пікірлер",
    viewDetails: "Толығырақ",
    home: "Басты бет",
    productNotFound: "Өнім табылмады",
    productNotFoundDesc: "Сіз іздеген өнім жоқ немесе жойылған.",
    backToProducts: "Өнімдерге оралу",
    addedToCart: "Себетке қосылды",
    addedToCartDesc: "себетке қосылды",
    addedToWishlist: "Таңдаулыларға қосылды",
    addedToWishlistDesc: "таңдаулыларға қосылды",
    active_users: "Белсенді пайдаланушылар",
    loading_users: "Пайдаланушылар жүктелуде...",
  },
  kg: {
    welcome: "Кош келиңиз",
    login: "Кирүү",
    register: "Каттоо",
    dashboard: "Башкаруу панели",
    profile: "Профиль",
    earnings: "Киреше",
    referrals: "Рефералдар",
    tariffs: "Тариф пландары",
    withdrawal: "Акча чыгаруу",
    spin: "Спин оюну",
    support: "Колдоо",
    phone: "Телефон номери",
    password: "Сырсөз",
    verify: "Текшерүү",
    submit: "Жөнөтүү",
    name: "Аты",
    activeTariff: "Активдүү тариф",
    daysRemaining: "Калган күндөр",
    dailyEarnings: "Күндүк киреше",
    monthlyEarnings: "Айлык киреше",
    invitedFriends: "Чакырылган достор",
    paymentStatus: "Төлөм абалы",
    purchase: "Сатып алуу",
    pay: "Төлөө",
    waitPayment: "Күтө туруңуз. Карта номери 2 мүнөттүн ичинде берилет",
    completePayment: "Төлөмдү аяктап, 10 мүнөттүн ичинде квитанцияны жүктөңүз",
    uploadReceipt: "Квитанцияны жүктөө",
    cardNumber: "Карта номери",
    requestWithdrawal: "Акча чыгарууну суроо",
    minimumAmount: "Минималдуу сумма",
    pending: "Күтүлүүдө",
    processed: "Иштелди",
    freeSpin: "Бекер айлануу",
    spinCount: "Айлануу саны",
    share: "Бөлүшүү",
    notFound: "404 Барак табылган жок",
    backToHome: "Башкы бетке кайтуу",
    start: "Баштоо",
    silver: "Күмүш",
    gold: "Алтын",
    price: "Баа",
    duration: "Узактыгы",
    dailyProfit: "Күндүк пайда",
    description: "Сүрөттөмө",
    days: "күн",
    or: "Же",
    with: "аркылуу",
    email: "Электрондук почта",
    optional: "Милдеттүү эмес",
    verificationCodeSent: "Текшерүү коду жөнөтүлдү:",
    yourReferralLink: "Сиздин реферал шилтемеңиз",
    copyLink: "Шилтемени көчүрүү",
    linkCopied: "Шилтеме көчүрүлдү!",
    shareVia: "Бөлүшүү",
    referralStats: "Реферал статистикасы",
    totalReferrals: "Бардык рефералдар",
    activeReferrals: "Активдүү рефералдар",
    referralEarnings: "Реферал кирешеси",
    productPrice: "Продукт баасы",
    dailyIncome: "Күнүмдүк киреше",
    incomeDuration: "Киреше мөөнөтү",
    totalIncome: "Жалпы киреше",
    tariffPrice: "Тариф баасы",
    information: "Маалымат",
    changePassword: "Сырсөздү өзгөртүү",
    changePasswordDesc:
      "Эсебиңиздин коопсуздугун камсыздоо үчүн сырсөзүңүздү жаңыртыңыз",
    currentPassword: "Учурдагы сырсөз",
    newPassword: "Жаңы сырсөз",
    confirmPassword: "Сырсөздү ырастоо",
    changing: "Өзгөртүлүүдө...",
    editPersonalInfo: "Жеке маалыматты түзөтүү",
    yourPersonalInfo: "Сиздин жеке маалыматыңыз",
    cancel: "Жокко чыгаруу",
    saveProfile: "Профилди сактоо",
    editProfile: "Профилди түзөтүү",
    userId: "Колдонуучу ID",
    editCardInfo: "Карта маалыматын түзөтүү",
    manageCardInfo: "Төлөм картасын башкаруу",
    expiryDate: "Жарактуулук мөөнөтү",
    expires: "Мөөнөтү",
    saveCard: "Картаны сактоо",
    editCard: "Картаны түзөтүү",
    addCard: "Карта кошуу",
    earningsHistory: "Киреше тарыхы",
    registeredSince: "Катталган күнү",
    daily: "Күнүмдүк",
    weekly: "Жумалык",
    monthly: "Айлык",
    aboutUs: "Биз жөнүндө",
    aboutUsDesc:
      "MLM платформабыз жана анын иштөө тартиби жөнүндө көбүрөөк билүү",
    ourMission: "Биздин миссиябыз",
    ourMissionDesc:
      "Биздин миссиябыз - бардыгына ачык жана кирешелүү MLM платформасын сунуштоо. Биз сапаттуу продукттар жана адилеттүү сыйлык планы аркылуу финансылык өсүү мүмкүнчүлүктөрүн түзүүгө ишенебиз.",
    ourMissionDesc2:
      "Биз өнөктөштөрүбүзгө туруктуу бизнес курууга жана финансылык көз карандысыздыкка жетүүгө мүмкүнчүлүк берүү менен бирге, ден соолук жана сулуулук үчүн премиум продукттарды сунуштоого умтулабыз.",
    howItWorks: "Бул кандай иштейт",
    joinUs: "Бизге кошулуңуз",
    joinUsDesc:
      "Платформабызда катталып, жеке эсебиңизди түзүңүз. Бул акысыз жана бир нече мүнөт убакыт алат.",
    chooseTariff: "Тарифти тандаңыз",
    chooseTariffDesc:
      "Максаттарыңызга жана бюджетиңизге ылайык келген тариф планын тандаңыз. Ар бир план ар кандай артыкчылыктарды жана киреше мүмкүнчүлүктөрүн сунуштайт.",
    earnMoney: "Акча табыңыз",
    earnMoneyDesc:
      "Тарифиңизден күнүмдүк киреше алууну баштаңыз жана рефералдар аркылуу кирешеңизди жогорулатуу үчүн тармагыңызды өнүктүрүңүз.",
    readyToStart: "Баштоого даярсызбы?",
    readyToStartDesc:
      "MLM платформабыз менен мурунтан эле акча табып жаткан миңдеген ийгиликтүү өнөктөштөргө кошулуңуз.",
    getStarted: "Баштоо",
    viewTariffs: "Тарифтерди көрүү",
    products: "Продукттар",
    about: "Биз жөнүндө",
    referralBonusInfo:
      "Рефералдарыңыз катталганда жана балансын толтурганда бонус аласыз.",
    shareReferralLink: "Реферал шилтемесин бөлүшүү",
    copied: "Көчүрүлдү!",
    referralLinkCopied: "Реферал шилтемеси көчүрүлдү!",
    joinMlmPlatform: "MLM платформасына кошулуңуз",
    joinMeOnMlm: "MLM платформасында мага кошулуп, акча табууну баштаңыз!",
    selectCard: "Картаны тандаңыз",
    amount: "Сумма",
    availableBalance: "Жеткиликтүү баланс",
    processing: "Иштетилүүдө...",
    withdrawalHistory: "Акча чыгаруу тарыхы",
    withdrawalPendingApproval:
      "Акча чыгаруу сурооңуз администратордун бекитүүсүн күтүүдө.",
    addNewCard: "Жаңы карта кошуу",
    skincare: "Тери кароо",
    supplements: "Кошумчалар",
    wellness: "Ден соолук",
    category: "Категория",
    quantity: "Саны",
    addToCart: "Себетке кошуу",
    addToWishlist: "Каалоолор тизмесине кошуу",
    features: "Өзгөчөлүктөрү",
    usage: "Колдонуу",
    ingredients: "Курамы",
    relatedProducts: "Окшош продукттар",
    reviews: "пикирлер",
    viewDetails: "Толугураак",
    home: "Башкы бет",
    productNotFound: "Продукт табылган жок",
    productNotFoundDesc: "Сиз издеген продукт жок же алынып салынган.",
    backToProducts: "Продукттарга кайтуу",
    addedToCart: "Себетке кошулду",
    addedToCartDesc: "себетке кошулду",
    addedToWishlist: "Каалоолор тизмесине кошулду",
    addedToWishlistDesc: "каалоолор тизмесине кошулду",
    active_users: "Активдүү колдонуучулар",
    loading_users: "Колдонуучулар жүктөлүүдө...",
  },
  tj: {
    welcome: "Хуш омадед",
    login: "Воридшавӣ",
    register: "Бақайдгирӣ",
    dashboard: "Лавҳаи идоракунӣ",
    profile: "Профил",
    earnings: "Даромад",
    referrals: "Рефералҳо",
    tariffs: "Нақшаҳои тарифӣ",
    withdrawal: "Гирифтани пул",
    spin: "Бозии Спин",
    support: "Дастгирӣ",
    phone: "Рақами телефон",
    password: "Рамз",
    verify: "Тасдиқ",
    submit: "Фиристодан",
    name: "Ном",
    activeTariff: "Тарифи фаъол",
    daysRemaining: "Рӯзҳои боқимонда",
    dailyEarnings: "Даромади рӯзона",
    monthlyEarnings: "Даромади моҳона",
    invitedFriends: "Дӯстони даъватшуда",
    paymentStatus: "Ҳолати пардохт",
    purchase: "Харидан",
    pay: "Пардохт",
    waitPayment:
      "Лутфан интизор шавед. Рақами корт дар давоми 2 дақиқа пешниҳод карда мешавад",
    completePayment:
      "Пардохтро анҷом диҳед ва дар давоми 10 дақиқа расидро бор кунед",
    uploadReceipt: "Бор кардани расид",
    cardNumber: "Рақами корт",
    requestWithdrawal: "Дархости гирифтани пул",
    minimumAmount: "Маблағи ҳадди ақал",
    pending: "Дар интизорӣ",
    processed: "Коркардшуда",
    freeSpin: "Чархзании ройгон",
    spinCount: "Шумораи чархзаниҳо",
    share: "Мубодила",
    notFound: "404 Саҳифа ёфт нашуд",
    backToHome: "Бозгашт ба саҳифаи асосӣ",
    start: "Оғоз",
    silver: "Нуқра",
    gold: "Тилло",
    price: "Нарх",
    duration: "Давомнокӣ",
    dailyProfit: "Фоидаи рӯзона",
    description: "Тавсиф",
    days: "рӯз",
    or: "Ё",
    with: "тавассути",
    email: "Почтаи электронӣ",
    optional: "Ихтиёрӣ",
    verificationCodeSent: "Рамзи тасдиқ фиристода шуд:",
    yourReferralLink: "Пайванди реферали шумо",
    copyLink: "Нусхабардории пайванд",
    linkCopied: "Пайванд нусхабардорӣ шуд!",
    shareVia: "Мубодила тавассути",
    referralStats: "Омори рефералҳо",
    totalReferrals: "Ҳамаи рефералҳо",
    activeReferrals: "Рефералҳои фаъол",
    referralEarnings: "Даромад аз рефералҳо",
    productPrice: "Нархи маҳсулот",
    dailyIncome: "Даромади рӯзона",
    incomeDuration: "Муддати даромад",
    totalIncome: "Даромади умумӣ",
    tariffPrice: "Нархи тариф",
    information: "Маълумот",
    changePassword: "Тағйири рамз",
    changePasswordDesc:
      "Рамзи худро барои нигоҳ доштани амнияти ҳисоби худ нав кунед",
    currentPassword: "Рамзи ҷорӣ",
    newPassword: "Рамзи нав",
    confirmPassword: "Тасдиқи рамз",
    changing: "Тағйир дода истодааст...",
    editPersonalInfo: "Таҳрири маълумоти шахсӣ",
    yourPersonalInfo: "Маълумоти шахсии шумо",
    cancel: "Бекор кардан",
    saveProfile: "Сабти профил",
    editProfile: "Таҳрири профил",
    userId: "ID корбар",
    editCardInfo: "Таҳрири маълумоти корт",
    manageCardInfo: "Идоракунии корти пардохт",
    expiryDate: "Мӯҳлати амал",
    expires: "Мӯҳлат",
    saveCard: "Сабти корт",
    editCard: "Таҳрири корт",
    addCard: "Илова кардани корт",
    earningsHistory: "Таърихи даромад",
    registeredSince: "Аз вақти бақайдгирӣ",
    daily: "Рӯзона",
    weekly: "Ҳафтаина",
    monthly: "Моҳона",
    aboutUs: "Дар бораи мо",
    aboutUsDesc:
      "Дар бораи платформаи MLM-и мо ва тарзи кори он маълумоти бештар гиред",
    ourMission: "Рисолати мо",
    ourMissionDesc:
      "Рисолати мо пешниҳоди платформаи шаффоф ва сердаромади MLM барои ҳама мебошад. Мо ба эҷоди имкониятҳо барои рушди молиявӣ тавассути маҳсулоти босифат ва нақшаи одилонаи подош бовар дорем.",
    ourMissionDesc2:
      "Мо барои пешниҳоди маҳсулоти аълосифати тандурустӣ ва зебоӣ кӯшиш мекунем, дар ҳоле ки ба шарикони мо имкон медиҳем, ки тиҷорати устувор бунёд кунанд ва ба мустақилияти молиявӣ ноил шаванд.",
    howItWorks: "Чӣ тавр кор мекунад",
    joinUs: "Ба мо ҳамроҳ шавед",
    joinUsDesc:
      "Дар платформаи мо ба қайд гиред ва ҳисоби шахсии худро созед. Ин ройгон аст ва танҳо якчанд дақиқа вақт мегирад.",
    chooseTariff: "Тарифро интихоб кунед",
    chooseTariffDesc:
      "Нақшаи тарифиеро интихоб кунед, ки ба ҳадафҳо ва буҷети шумо мувофиқ бошад. Ҳар як нақша манфиатҳо ва имкониятҳои гуногуни даромад пешниҳод мекунад.",
    earnMoney: "Пул кор кунед",
    earnMoneyDesc:
      "Аз тарифи худ даромади ҳаррӯза гирифтанро оғоз кунед ва шабакаи худро барои зиёд кардани даромади худ тавассути рефералҳо рушд диҳед.",
    readyToStart: "Барои оғоз омодаед?",
    readyToStartDesc:
      "Ба ҳазорҳо шарикони муваффақ, ки аллакай бо платформаи MLM-и мо пул кор мекунанд, ҳамроҳ шавед.",
    getStarted: "Оғоз кунед",
    viewTariffs: "Дидани тарифҳо",
    products: "Маҳсулот",
    about: "Дар бораи мо",
    referralBonusInfo:
      "Вақте ки рефералҳои шумо ба қайд гирифта мешаванд ва ба тавозуни худ маблағ илова мекунанд, шумо бонус мегиред.",
    shareReferralLink: "Мубодилаи пайванди реферал",
    copied: "Нусхабардорӣ шуд!",
    referralLinkCopied: "Пайванди реферал ба буфери мубодила нусхабардорӣ шуд!",
    joinMlmPlatform: "Ба платформаи MLM ҳамроҳ шавед",
    joinMeOnMlm:
      "Ба ман дар платформаи MLM ҳамроҳ шавед ва пул кор карданро оғоз кунед!",
    selectCard: "Кортро интихоб кунед",
    amount: "Маблағ",
    availableBalance: "Тавозуни дастрас",
    processing: "Коркард...",
    withdrawalHistory: "Таърихи гирифтани пул",
    withdrawalPendingApproval:
      "Дархости гирифтани пули шумо дар интизори тасдиқи маъмур аст.",
    addNewCard: "Илова кардани корти нав",
    skincare: "Нигоҳубини пӯст",
    supplements: "Иловаҳо",
    wellness: "Тандурустӣ",
    category: "Категория",
    quantity: "Миқдор",
    addToCart: "Ба сабад илова кунед",
    addToWishlist: "Ба рӯйхати дӯстдошта илова кунед",
    features: "Хусусиятҳо",
    usage: "Истифода",
    ingredients: "Таркиб",
    relatedProducts: "Маҳсулоти монанд",
    reviews: "тақризҳо",
    viewDetails: "Дидани тафсилот",
    home: "Асосӣ",
    productNotFound: "Маҳсулот ёфт нашуд",
    productNotFoundDesc:
      "Маҳсулоте, ки шумо ҷустуҷӯ мекунед, вуҷуд надорад ё хориҷ карда шудааст.",
    backToProducts: "Бозгашт ба маҳсулот",
    addedToCart: "Ба сабад илова карда шуд",
    addedToCartDesc: "ба сабади шумо илова карда шуд",
    addedToWishlist: "Ба рӯйхати дӯстдошта илова карда шуд",
    addedToWishlistDesc: "ба рӯйхати дӯстдоштаи шумо илова карда шуд",
    active_users: "Истифодабарандагони фаъол",
    loading_users: "Истифодабарандагон боргузорӣ мешаванд...",
  },
  cn: {
    welcome: "欢迎",
    login: "登录",
    register: "注册",
    dashboard: "控制面板",
    profile: "个人资料",
    earnings: "收益",
    referrals: "推荐人",
    tariffs: "资费计划",
    withdrawal: "提款",
    spin: "旋转游戏",
    support: "支持",
    phone: "电话号码",
    password: "密码",
    verify: "验证",
    submit: "提交",
    name: "姓名",
    activeTariff: "当前资费",
    daysRemaining: "剩余天数",
    dailyEarnings: "日收益",
    monthlyEarnings: "月收益",
    invitedFriends: "邀请的朋友",
    paymentStatus: "支付状态",
    purchase: "购买",
    pay: "支付",
    waitPayment: "请稍等。卡号将在2分钟内提供",
    completePayment: "请在10分钟内完成支付并上传收据",
    uploadReceipt: "上传收据",
    cardNumber: "卡号",
    requestWithdrawal: "申请提款",
    minimumAmount: "最低金额",
    pending: "待处理",
    processed: "已处理",
    freeSpin: "免费旋转",
    spinCount: "旋转次数",
    share: "分享",
    notFound: "404 页面未找到",
    backToHome: "返回首页",
    start: "开始",
    silver: "银",
    gold: "金",
    price: "价格",
    duration: "持续时间",
    dailyProfit: "日利润",
    description: "描述",
    days: "天",
    or: "或",
    with: "使用",
    email: "电子邮件",
    optional: "可选",
    verificationCodeSent: "验证码已发送至:",
    yourReferralLink: "您的推荐链接",
    copyLink: "复制链接",
    linkCopied: "链接已复制到剪贴板！",
    shareVia: "分享方式",
    referralStats: "推荐统计",
    totalReferrals: "总推荐人数",
    activeReferrals: "活跃推荐人数",
    referralEarnings: "推荐收益",
    productPrice: "产品价格",
    dailyIncome: "每日收入",
    incomeDuration: "收入期限",
    totalIncome: "总收入",
    tariffPrice: "资费价格",
    information: "信息",
    changePassword: "修改密码",
    changePasswordDesc: "更新您的密码以保持账户安全",
    currentPassword: "当前密码",
    newPassword: "新密码",
    confirmPassword: "确认密码",
    changing: "正在修改...",
    editPersonalInfo: "编辑个人信息",
    yourPersonalInfo: "您的个人信息",
    cancel: "取消",
    saveProfile: "保存资料",
    editProfile: "编辑资料",
    userId: "用户ID",
    editCardInfo: "编辑卡信息",
    manageCardInfo: "管理支付卡",
    expiryDate: "有效期",
    expires: "到期",
    saveCard: "保存卡",
    editCard: "编辑卡",
    addCard: "添加卡",
    earningsHistory: "收益历史",
    registeredSince: "注册时间",
    daily: "每日",
    weekly: "每周",
    monthly: "每月",
    aboutUs: "关于我们",
    aboutUsDesc: "了解更多关于我们的MLM平台及其工作原理",
    ourMission: "我们的使命",
    ourMissionDesc:
      "我们的使命是为每个人提供透明且有利可图的MLM平台。我们相信通过优质产品和公平的补偿计划创造财务增长机会。",
    ourMissionDesc2:
      "我们致力于提供优质的健康和美容产品，同时使我们的合作伙伴能够建立可持续的业务并实现财务独立。",
    howItWorks: "工作原理",
    joinUs: "加入我们",
    joinUsDesc:
      "在我们的平台上注册并创建您的个人账户。这是免费的，只需几分钟。",
    chooseTariff: "选择资费",
    chooseTariffDesc:
      "选择适合您目标和预算的资费计划。每个计划提供不同的福利和收益潜力。",
    earnMoney: "赚钱",
    earnMoneyDesc:
      "开始从您的资费中获得每日收入，并建立您的网络以通过推荐增加您的收入。",
    readyToStart: "准备开始？",
    readyToStartDesc: "加入已经在我们的MLM平台上赚钱的数千名成功合作伙伴。",
    getStarted: "开始",
    viewTariffs: "查看资费",
    products: "产品",
    about: "关于",
    referralBonusInfo: "当您的推荐人注册并向余额添加资金时，您将获得奖金。",
    shareReferralLink: "分享推荐链接",
    copied: "已复制！",
    referralLinkCopied: "推荐链接已复制到剪贴板！",
    joinMlmPlatform: "加入MLM平台",
    joinMeOnMlm: "加入我的MLM平台并开始赚钱！",
    selectCard: "选择卡",
    amount: "金额",
    availableBalance: "可用余额",
    processing: "处理中...",
    withdrawalHistory: "提款历史",
    withdrawalPendingApproval: "您的提款请求正在等待管理员批准。",
    addNewCard: "添加新卡",
    skincare: "护肤",
    supplements: "补充剂",
    wellness: "健康",
    category: "类别",
    quantity: "数量",
    addToCart: "添加到购物车",
    addToWishlist: "添加到愿望清单",
    features: "特点",
    usage: "使用方法",
    ingredients: "成分",
    relatedProducts: "相关产品",
    reviews: "评论",
    viewDetails: "查看详情",
    home: "首页",
    productNotFound: "产品未找到",
    productNotFoundDesc: "您正在寻找的产品不存在或已被移除。",
    backToProducts: "返回产品",
    addedToCart: "已添加到购物车",
    addedToCartDesc: "已添加到您的购物车",
    addedToWishlist: "已添加到愿望清单",
    addedToWishlistDesc: "已添加到您的愿望清单",
    active_users: "活跃用户",
    loading_users: "加载用户中...",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useLocalStorage<Language>(
    "language",
    "ru"
  );
  const [currency, setCurrency] = useState<Currency>(
    languageCurrencyMap[language]
  );

  useEffect(() => {
    setCurrency(languageCurrencyMap[language]);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    setCurrency(languageCurrencyMap[lang]);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currency, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
